#!/usr/bin/env sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "$branch branch executing install and build"
  # TODO: Find a way to only run when package-lock.json is modified
  npm install

  # create folder structure for backup
  mkdir -p ./backup/client
  mkdir -p ./backup/server/logs

  # save .htaccess for NodeJs application
  if [ -e ./dist/client/.htaccess ]; then
    mv ./dist/client/.htaccess ./backup/client/
  fi

  #  save the server logs
  if [ -d ./dist/server/logs ]; then
    if compgen -G "./dist/server/logs/*.log" > /dev/null; then
      mv ./dist/server/logs/*.log ./backup/server/logs/
    fi
  fi

  # build the app
  npm run build

  # add the .shtml of 404
   if [ -e ./dist/client/404.html ]; then
    cp ./dist/client/404.html ./dist/client/404.shtml
  fi

  # restore .htaccess for NodeJs application
  if [ -e ./backup/client/.htaccess ]; then
    mv ./backup/client/.htaccess ./dist/client/
  fi

  # restore the server logs
  mkdir -p ./dist/server/logs
  if [ -d ./backup/server/logs ]; then
    if compgen -G "./backup/server/logs/*.log" > /dev/null; then
      mv ./backup/server/logs/*.log ./dist/server/logs/
    fi
  fi

  # generate the node application entry point
  if [ -d ./dist/server ]; then
    echo "import(\"./entry.mjs\");" > ./dist/server/entry.cjs
  fi

fi