#!/usr/bin/env sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "$branch branch executing install and build"
  # TODO: Find a way to only run when package-lock.json is modified
  npm install
  npm run build
fi